### ISSUE TITLE
Deselect Color

### ISSUE THREAD

**Issue by pxwee5** [heyday/silverstripe-colorpalette#13]
Feature request:

This plugin needs a way to de-select colors. This gives us flexibility to de-select color and use the default color on our elements.

**Comment by lucasfrey** [comment]
That's a good point, we will look into it

**Comment by jackkemmish** [comment]
Hey @lucasfrey, was this ever looked into?

**Comment by xini** [comment]
@jackkemmish have you had a look at https://github.com/fromholdio/silverstripe-colorpalette? Maybe it's fixed there?

**Comment by wilr** [comment]
@pxwee5 As this is powered by an OptionsetField (which naturally don't have an unselect option) I think you're best to mark a default colour in your options list like this. This will add a '' option with an icon to indicate a 'clear' state. You can change the icon / colour if you need

```
$fields->addFieldToTab(
    'Root.Main',
    Heyday\ColorPalette\Fields\ColorPaletteField::create(
        'BackgroundColor',
        'Background Color',
        [
        '' => 'url(\'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" opacity="0.2" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="4.93" y1="4.93" x2="19.07" y2="19.07"></line></svg>\') no-repeat center center',
        'gradient' => 'linear-gradient(#e66465, #9198e5);',
        'light' => '#FFFFFF',
        'yellow' => '#FCD633',
        'purple' => '#4A32AA',
        ]
    )
);
```

![Screenshot 2023-12-21 at 10 52 33 AM](https://github.com/heyday/silverstripe-colorpalette/assets/101629/b56de6bb-0f99-4cbb-bea4-23aded528189)
