### ISSUE TITLE
CMS sometimes uses react template, breaking CSS

### ISSUE THREAD

**Issue by sheadawson** [heyday/silverstripe-colorpalette#15]
SS 4.5.1 Elemental 4.3.0 

If I put a ColorPaletteField in an ElementalBlock, it gets rendered with the OptionsetField React Component template, which has different markup to ColorPaletteField.ss and doesn't apply the inline style (background-color) to the options.

I think a ColorPaletteField React component should be created for SS admin?

**Comment by lucasfrey** [comment]
Hi sheadawson,

I haven't had the chance to play with SilverStripe 4.5.1 yet. PR is welcome if you find the time, I'll be happy to review it.

**Comment by wilr** [comment]
Note as a workaround (since I've just found this issue) is to disable inline editing on the Elemental block. But yes, a react component is high priority!
