### ISSUE TITLE
Consider namespacing or a submodule?

### ISSUE THREAD

**Issue by camfindlay** [heyday/silverstripe-colorpalette#4]
Just run into a case where another module used alongside this one had the same Field subclass name.
https://github.com/heyday/silverstripe-colorpalette/blob/master/code/ColorPaletteField.php and https://github.com/titledk/silverstripe-calendar/blob/master/code/colors/ColorpaletteField.php

Options might be to namespace OR module maintainers could talk and look to see if a shared ColorPaletteField class might be preferable. @camspiers @titledk :)

**Comment by camspiers** [comment]
I'm easy either way, but it would be a major version change simply for the namespacing. @stecman what do you think?

**Comment by stecman** [comment]
It looks like these are compatible in terms of storage, so I'd be interested to see a PR for `DropdownColorPaletteField` and go the merging route. Namespacing will need to happen at some stage though.
