### ISSUE TITLE
GroupedColorPaletteField doesn't validate

### ISSUE THREAD

**Issue by silverstripe-elliot** [heyday/silverstripe-colorpalette#7]
If you try to save a value to an 8x2 grid of colours, a validation error is thrown.

`Please select a value within the list provided. {{your colour}} is not a valid option`

My array looks like this:

```
        'Darks' => [
            ...
            '#E61016' => '#E61016',
        ],
        'Lights' => [
            ...
            '#21B097' => '#21B097'
        ],
```
GroupedColorPaletteField doesn't implement a `validate()` method, so it inherits from DropdownField. `DropdownField::validate()` only accepts a single dimensional array.

You can subclass the field and overload the `validate` function in your subclass to get around it

**Comment by stevie-mayhew** [comment]
I think that this is a problem with CheckboxSetField or OptionsetField in framework. See also https://github.com/silverstripe/silverstripe-userforms/issues/548

**Comment by lucasfrey** [comment]
I reckon that pull request is fixing that issue:
https://github.com/heyday/silverstripe-colorpalette/pull/8

I just tried locally and it seems to work fine. @stevie-mayhew what do you think ?

**Comment by stevie-mayhew** [comment]
@lucasfrey I've run through and tested, seems good. Merge away!
